name: kitaby_flutter
description: "A Flutter application for tracking reading progress and challenges."
# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjusted SDK constraint for modern Dart

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this for localization/RTL support
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.6 # Included by default, good for iOS style icons
  google_fonts: ^6.1.0 # For using Google Fonts like Cairo
  percent_indicator: ^4.2.3 # For progress bars/circles

  # State Management
  provider: ^6.0.5 # Simple state management

  # Data Persistence
  shared_preferences: ^2.2.2 # Local key-value storage
  path_provider: ^2.1.1 # Access file system paths
  path: ^1.8.3 # Path manipulation utilities

  # Utilities
  intl: ^0.19.0 # Internationalization and date formatting
  uuid: ^4.2.1 # Generating unique IDs
  image_picker: ^1.0.4 # Picking images from gallery/camera
  file_picker: ^6.1.1 # Alternative for file picking (optional)


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Code linting

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Regular.ttf
        - asset: fonts/Cairo-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
